services:

  prestart:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: bash scripts/prestart.sh
    env_file:
      - ./backend/.env

  backend:
    restart: "no"
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      prestart:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    env_file:
      - ./backend/.env
    volumes:
      - app-uploads:/app/backend/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild

  frontend:
    restart: "no"
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development
    ports:
      - "5173:80"

volumes:
  app-uploads:
